schedule_app/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from accounts.views import user_register, company_register, UserLoginView


app_name = 'accounts'

urlpatterns = [
    path('', UserLoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('user_register/', user_register, name='user_register'),
    path('company_register/', company_register, name='company_register'),
]

schedule_app/schedule/urls.py
from django.urls import path
from schedule.views import (main_page, CalendarView,
                            CreateEventView, UpdateEventView,
                            WorkersView, DeleteWorkersView,
                            AvaibilityView, CreateAvaibilityView,
                            TimetableView, TimetableSettingsView,
                            CreateSettingsView,)


app_name = 'schedule'

urlpatterns = [
    path('main_page/', main_page, name='main_page'),
    path('month_calendar/', CalendarView.as_view(), name='month_calendar'),
    path('create_event/', CreateEventView.as_view(), name='create_event'),
    path('update_event/<int:pk>/', UpdateEventView.as_view(), name='update_event'),

    path('workers_list/', WorkersView.as_view(), name='workers_view'),
    path('worker_delete/<int:pk>/', DeleteWorkersView.as_view(), name='worker_delete'),
    
    path('availability/', AvaibilityView.as_view(), name='avaibility'),
    path('create_availability/', CreateAvaibilityView.as_view(), name='create_avaibility'),
    
    path('timetable/', TimetableView.as_view(), name='timetable'),
    
    path('generate/', TimetableSettingsView.as_view(), name='generate'),
    path('create_settings/', CreateSettingsView.as_view(), name='create_settings')
]

schedule_app/schedule_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('schedule/', include('schedule.urls'))
]

schedule_app/base/models.py
from django.db import models
from django.contrib.auth.models import User

import uuid
from datetime import datetime


class InvitationCode(models.Model):
    company = models.ForeignKey('Company', on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    code = models.CharField(max_length=6)
    is_used = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.code}'
    

class Company(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    
    def generate_invitation_code(self, custom_code=None):
        if custom_code:
            code = custom_code
        else:
            code = uuid.uuid4().hex[:6].upper()
        InvitationCode.objects.create(company=self, code=code)
        return code
    
    def __str__(self) -> str:
        return self.name
        

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    inv_code = models.ForeignKey(InvitationCode, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name}'


class Event(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    
    def __str__(self):
        return self.name
    

class Timetable(models.Model):
    day = models.DateField()
    start = models.TimeField()
    end = models.TimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return str(self.day)


class Availability(models.Model):
    availability_day = models.DateField()
    availability_start = models.TimeField()
    availability_end = models.TimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    upload = models.BooleanField(default=False, blank=True, null=True)
    
    def __str__(self):
        return str(self.availability_day)
    
    
class TimetableSettings(models.Model):
    people = models.IntegerField(default=2)
    start_time = models.TimeField()
    end_time = models.TimeField()
    work_days = models.JSONField(default=list)
    justice = models.BooleanField(default=True)
    min_length = models.IntegerField(default=4)

schedule_app/base/forms.py
from django import forms
from django.forms import DateInput
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from base.models import Profile, User, Company, InvitationCode, Event, Availability, Timetable, TimetableSettings
from django.utils.functional import cached_property


class UserForm(UserCreationForm):
    inv_code = forms.CharField(required=True)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'inv_code', 'password1', 'password2']

    def clean_inv_code(self):
        inv_code = self.cleaned_data.get('inv_code')
        if not InvitationCode.objects.filter(code=inv_code, is_used=False):
            raise forms.ValidationError("Podany kod jest nieprawidłowy lub został już użyty")
        return inv_code


class CompanyForm(forms.ModelForm):
    custom_inv_code = forms.CharField(required=True, label="Kod do przyszłego logowania")
    email = forms.EmailField(required=True)

    class Meta:
        model = Company
        fields = ['name', 'email', 'custom_inv_code']


class UserCompanyForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password1', 'password2']


class UserLoginForm(AuthenticationForm):
    inv_code = forms.CharField(label="Kod zaproszenia")

    def clean(self):
        cleaned_data = super().clean()
        inv_code = cleaned_data.get('inv_code')

        username = self.cleaned_data.get('username')
        if username:
            user = User.objects.filter(username=username).first()
            if user:
                if not InvitationCode.objects.filter(user=user, code=inv_code):
                    raise forms.ValidationError("Nieprawidłowy kod zaproszenia")
        return cleaned_data


class CreateEventForm(forms.ModelForm):
    class Meta:
        model = Event
        widgets = {
        'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = ['name', 'description', 'start_time', 'end_time']
        

class CreateAvailabilityForm(forms.ModelForm):
    class Meta:
        model = Availability
        widgets = {
            'availability_day': forms.DateInput(attrs={'type': 'date'}),
            'availability_start': forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'),
            'availability_end': forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'),
        }
        fields = ['availability_day', 'availability_start', 'availability_end']


class TimetableForm(forms.ModelForm):
    class Meta:
        model = Timetable
        widgets = {
            'day': forms.DateInput(attrs={'type': 'date'}),
            'start': forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'),
            'end': forms.TimeInput(attrs={'type': 'time'}, format='%H:%M'),
        }
        fields = ['user', 'day', 'start', 'end']


class TimetableSettingsForm(forms.ModelForm):
    class Meta:
        model = TimetableSettings
        fields = ['people', 'start_time', 'end_time', 'work_days', 'justice', 'min_length']

schedule_app/schedule/views.py
import json
from typing import Any
from django.db import transaction
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponseRedirect
from django.http.response import HttpResponse as HttpResponse
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (ListView, CreateView,
                                  UpdateView, DetailView,
                                  DeleteView, View)
from django.utils.safestring import mark_safe
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from base.forms import CreateEventForm, CreateAvailabilityForm, TimetableForm, TimetableSettingsForm
from base.models import Event, InvitationCode, Profile, Company, Availability, User, Timetable, TimetableSettings
from schedule.utils import UserCalendar, get_week_dates
from base.decorators import check_user_able_to_see_page

from datetime import datetime, date
import calendar
from calendar import HTMLCalendar
from datetime import timedelta

from django.db.models.functions import TruncDay
from collections import defaultdict

@login_required()
def main_page(request):
    return render(request, 'schedule/main_page.html')


class CalendarView(ListView, LoginRequiredMixin):
    model = Event
    template_name = 'schedule/month_calendar.html'
    
    def get_queryset(self):
        return Event.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        
        cal = UserCalendar(self.request.user, d.year, d.month)
        
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


class CreateEventView(CreateView, LoginRequiredMixin):
    model = Event
    form_class = CreateEventForm
    template_name = 'schedule/create_event.html'
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('schedule:month_calendar')
    

class UpdateEventView(UpdateView, LoginRequiredMixin):
    model = Event
    form_class = CreateEventForm
    template_name = 'schedule/update_event.html'
    
    def get_success_url(self):
        return reverse('schedule:month_calendar')


class WorkersView(ListView, LoginRequiredMixin):
    model = InvitationCode
    template_name = 'schedule/workers_list.html'
    context_object_name = 'codes'

    @method_decorator(check_user_able_to_see_page)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def get_queryset(self):
        company = get_object_or_404(Company, owner=self.request.user)
        return InvitationCode.objects.filter(company=company).select_related('user')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['show_generate_code_button'] = True
        return context

    def post(self, request, *args, **kwargs):
        company = Company.objects.get(owner=request.user)
        new_code = company.generate_invitation_code()
        return redirect(reverse('schedule:workers_view'))


class DeleteWorkersView(LoginRequiredMixin, DeleteView):
    model = InvitationCode
    template_name = 'schedule/workers_delete.html'
    success_url = reverse_lazy('schedule:workers_view')

    def get_queryset(self):
        company = get_object_or_404(Company, owner=self.request.user)
        return InvitationCode.objects.filter(company=company)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


class AvaibilityView(LoginRequiredMixin, ListView):
    template_name = 'schedule/availability.html'
    model = Availability
    context_object_name = 'availabilities'
    
    def get_queryset(self):
        return Availability.objects.filter(user=self.request.user, upload=False)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
    def post(self, request, *args, **kwargs):
        if 'upload_id' in request.POST:
            pk = request.POST.get('upload_id')
            availability = get_object_or_404(Availability, pk=pk, user=request.user)
            availability.upload = True
            availability.save()
            return HttpResponseRedirect(request.path_info)  # Odświeża stronę, zachowując ten sam URL
        return super().post(request, *args, **kwargs)
    

class CreateAvaibilityView(LoginRequiredMixin, CreateView):
    template_name = 'schedule/create_avaibility.html'
    model = Availability
    form_class = CreateAvailabilityForm
    
    def get_success_url(self):
        return reverse('schedule:avaibility')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TimetableView(LoginRequiredMixin, ListView):
    template_name = 'schedule/timetable.html'
    model = Availability
    context_object_name = 'availabilities'
    form_class = TimetableForm

    @method_decorator(check_user_able_to_see_page)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Availability.objects.filter(upload=True)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        week_offset = int(self.request.GET.get('week_offset', 0))
        today = datetime.now() + timedelta(weeks=week_offset)
        week_dates = get_week_dates(today)
        context['week_dates'] = {date: [] for date in week_dates}
        context['prev_week_url'] = prev_week(today, week_offset)
        context['next_week_url'] = next_week(today, week_offset)
        
        week_dates_timetable = get_week_dates(today)
        context['week_dates_timetable'] = {date: [] for date in week_dates_timetable}

        availabilities = self.get_queryset()
        timetables = Timetable.objects.all()
        context['timetables'] = timetables

        for availability in availabilities:
            if availability.availability_day in context['week_dates']:
                context['week_dates'][availability.availability_day].append(availability)
        
        for timetable in timetables:
            if timetable.day in context['week_dates_timetable']:
                context['week_dates_timetable'][timetable.day].append(timetable)

        if 'form' not in context:  
            context['form'] = self.form_class()
        return context
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            timetable = form.save(commit=False)
            timetable.save()
            return redirect('schedule:timetable')
        else:
            return self.render_to_response(self.get_context_data(form=form))


def get_week_offset(req_week):
    if req_week:
        return int(req_week)
    return 0

def prev_week(d, week_offset):
    return 'week_offset=' + str(week_offset - 1)

def next_week(d, week_offset):
    return 'week_offset=' + str(week_offset + 1)

def merge_shifts(shifts):
    merged = []
    for shift in sorted(shifts, key=lambda x: x['start']):
        if not merged or shift['start'] > merged[-1]['end']:
            merged.append(shift)
        else:
            merged[-1]['end'] = max(merged[-1]['end'], shift['end'])
    return merged


class TimetableSettingsView(LoginRequiredMixin, View):
    
    def get(self, request, *args, **kwargs):
        timetable_settings = TimetableSettings.objects.first()
        user_ids = Availability.objects.filter(upload=True).values_list('user', flat=True).distinct()
        available_workers = User.objects.filter(id__in=user_ids)
        work_days = json.loads(timetable_settings.work_days) if isinstance(timetable_settings.work_days, str) else timetable_settings.work_days
        print(work_days)
        self.generate_timetable(timetable_settings, available_workers)

        return redirect('schedule:timetable')
    
    def generate_timetable(self, timetable_settings, available_workers):
        with transaction.atomic():
            work_days = json.loads(timetable_settings.work_days) if isinstance(timetable_settings.work_days, str) else timetable_settings.work_days

            for day_name in work_days:
                day_index = self.get_weekday_index(day_name)
                for person in available_workers:
                    shifts_for_person = Availability.objects.filter(user=person, availability_day__week_day=day_index)

                    shifts_to_merge = [
                        {'start': shift.availability_start, 'end': shift.availability_end, 'availability_day': shift.availability_day}
                        for shift in shifts_for_person
                    ]
                    

schedule_app/schedule/templates/schedule/availability.html
{% extends 'schedule/base.html' %}
<!DOCTYPE html>
{% block content %}

<div class="container text-center">
<table>
    <thead>
      <tr>
        <th>Data</th>
        <th>Godzina rozpoczęcia</th>
        <th>Godzina zakończenia</th>
      </tr>
    </thead>
    <tbody>
        {% for availability in availabilities %}
        <tr>
            <td>{{ availability.availability_day }}</td>
            <td>{{ availability.availability_start|date:"H:i" }}</td>
            <td>{{ availability.availability_end|date:"H:i" }}</td>
            <td>
                <form method="post" action="{% url 'schedule:avaibility' %}">
                    {% csrf_token %}
                    <input type="hidden" name="upload_id" value="{{ availability.pk }}" />
                    <button type="submit" class="btn btn-success">Zgłoś</button>
                </form>
            </td>
        </tr>
        {% endfor %}
        
    </tbody>
  </table>
  <a href="{% url 'schedule:create_avaibility' %}" class="btn btn-primary">Dodaj dostępność</a>
</div>

{% endblock %}

schedule_app/schedule/templates/schedule/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <link rel="stylesheet" type="text/css" href="{% static 'schedule/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <title>Django Calendar App</title>
</head>
<body>
  <div class="navbar">
    <a href="{% url 'schedule:month_calendar' %}">Kalendarz</a>
    <a href="{% url 'schedule:main_page' %}">Strona Główna</a>
    <a href="{% url 'schedule:workers_view' %}">Moi pracownicy</a>
    <a href="{% url 'schedule:avaibility' %}">Dostępność</a>
    <a href="{% url 'schedule:timetable' %}">Grafik</a>
  </div>
  {% block content %}
  {% endblock %}
</body>
</html>

schedule_app/schedule/templates/schedule/create_avaibility.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
  </form>

schedule_app/schedule/templates/schedule/create_event.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
  </form>

schedule_app/schedule/templates/schedule/create_settings.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
</form>

schedule_app/schedule/templates/schedule/generate.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zrób</button>
</form>

schedule_app/schedule/templates/schedule/main_page.html
{% extends 'schedule/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>
    {% block content %}
    
    <h1>Hello {{ user.first_name }} {{ user.last_name }}</h1>

    {% endblock %}
</body>
</html>

schedule_app/schedule/templates/schedule/month_calendar.html
{% extends 'schedule/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>

</head>
<body>
   {% block content %}
   </br>
   <center><h1>Calendar</h1></center>
   <hr>
   <div class="clearfix">
      <a class="btn btn-outline-primary left" href="{% url 'schedule:month_calendar' %}?{{ prev_month }}"> Previous Month </a>
      <a class="btn btn-outline-primary right" href="{% url 'schedule:month_calendar' %}?{{ next_month }}"> Next Month </a>
      <a class="btn btn-outline-primary right " href="{% url 'schedule:create_event' %}"> Create Event </a>
  </div>  
    <h1>{{ calendar }}</h1>
   {% endblock %}
</body>
</html>

schedule_app/schedule/templates/schedule/test.html
{% extends 'schedule/base.html' %}
<!DOCTYPE html>
{% block content %}
<div class="week-calendar" style="display: flex; justify-content: space-around;">
    {% for date in week_dates %}
    <div>
        <p>{{ date|date:"D" }}</p>
        <p>{{ date|date:"d M Y" }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

schedule_app/schedule/templates/schedule/timetable.html
{% extends 'schedule/base.html' %}
<!DOCTYPE html>
{% block content %}
</br>
<center><h1>Dostępność twoich pracowników</h1></center>
<div>
    <a class="btn btn-outline-primary left" href="?{{ prev_week_url }}">Poprzedni tydzień</a>
    <a class="btn btn-outline-primary right" href="?{{ next_week_url }}">Następny tydzień</a>
</div>
<hr>
<div class="week-calendar" style="display: flex; justify-content: space-around;">

    {% for date, availabilities in week_dates.items %}
    <div>
        <p>{{ date|date:"D" }}</p>
        <p>{{ date|date:"d M Y" }}</p>
        {% for availability in availabilities %}
            <li>{{ availability.user.first_name }} {{ availability.user.last_name }} {{ availability.availability_start|date:"H:i" }} - {{ availability.availability_end|date:"H:i" }}</li>
        {% endfor %}
    </div>
    {% endfor %}
    
</div>
<hr>

<center><h1>Grafik</h1></center>

<hr>
<div class="week-calendar" style="display: flex; justify-content: space-around;">

    {% for date, timetables in week_dates_timetable.items %}
    <div>
        <p>{{ date|date:"D" }}</p>
        <p>{{ date|date:"d M Y" }}</p>
        {% for timetable in timetables %}
            <li>{{ timetable.user.first_name }} {{ timetable.user.last_name }} {{ timetable.start|date:"H:i" }} - {{ timetable.end|date:"H:i" }}</li>
        {% endfor %}
        </div>
    {% endfor %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Dodaj do grafiku</button>
</form>
</div>
<a class="btn btn-primary" href="{% url 'schedule:generate' %}"> Generuj Grafik </a>
{% endblock %}

schedule_app/schedule/templates/schedule/update_event.html
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zapisz</button>
  </form>

schedule_app/schedule/templates/schedule/workers_delete.html
{% extends 'schedule/base.html' %}

{% block content %}
    <div class='container text-center'>
    <h2>Czy na pewno chcesz usunąć ten kod "{{ object.code }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Usuń</button>
        <button class='btn btn-primary' href="{{ success_url }}">Anuluj</button>
    </form>
</div>
{% endblock %}

schedule_app/schedule/templates/schedule/workers_list.html
{% extends 'schedule/base.html' %}
<!DOCTYPE html>
{% block content %}
<div class="container text-center">
  <h2>Kody zaproszeń i pracownicy</h2>

  {% if show_generate_code_button %}
  <form method="post" class="mb-4">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Generuj nowy kod</button>
  </form>
  {% endif %}

  <ul class="list-group">
    {% for code in codes %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Kod: {{ code.code }}
        {% if code.user %}
          -- {{ code.user.first_name }} {{ code.user.last_name }}
        {% else %}
          Kod nieprzypisany
        {% endif %}
        <a href="{% url 'schedule:worker_delete' code.id %}" class="btn btn-danger btn-sm">Usuń</a>
      </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}