schedule_app/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from accounts.views import user_register, company_register, UserLoginView


app_name = 'accounts'

urlpatterns = [
    path('', UserLoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('user_register/', user_register, name='user_register'),
    path('company_register/', company_register, name='company_register'),
]

schedule_app/schedule_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('schedule/', include('schedule.urls'))
]

schedule_app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.http import HttpResponse
from base.models import User, Profile, Company, InvitationCode
from base.forms import UserForm, CompanyForm, UserCompanyForm, UserLoginForm


class UserLoginView(LoginView):
    form_class = UserLoginForm


def user_register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            inv_code = form.cleaned_data['inv_code']
            try:
                invitation = InvitationCode.objects.get(code=inv_code, is_used=False)
            except InvitationCode.DoesNotExist:
                return HttpResponse("Nieprawidłowy kod zaproszenia lub kod został już użyty.", status=400)

            user = form.save(commit=False)
            user.save()
            
            Profile.objects.create(user=user, inv_code=invitation)
            invitation.is_used = True
            invitation.user = user
            invitation.save()

            login(request, user)
            return redirect('accounts:login')
    else:
        form = UserForm
    return render(request, 'accounts/register_user.html', {'form': form})


def company_register(request):
    if request.method == 'POST':
        user_form = UserCompanyForm(request.POST)
        company_form = CompanyForm(request.POST)
        
        if user_form.is_valid() and company_form.is_valid():
            user = user_form.save()

            company = company_form.save(commit=False)
            company.owner = user
            company.save()
            
            custom_inv_code = company_form.cleaned_data['custom_inv_code']
            invitation_code = InvitationCode.objects.create(company=company, code=custom_inv_code, is_used=True)
            Profile.objects.create(user=user, inv_code=invitation_code)

            invitation_code.user = user
            invitation_code.save()

            login(request, user)
            return redirect('accounts:login')
    else:
        user_form = UserCompanyForm()
        company_form = CompanyForm()

    return render(request, 'accounts/register_company.html', {
        'user_form': user_form,
        'company_form': company_form
    })

schedule_app/accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dater - Aplikacja do Harmonogramów</title>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
</head>
<body>
<div class="container">
    <div class="left-column">
        <!-- Zdjęcia po lewej stronie -->
    </div>
    <div class="right-column">
        <h1>Dater aplikacji do harmonogramów</h1>
        <p>Aplikacja "Dater" to innowacyjne rozwiązanie dla menedżerów i zespołów HR, które ułatwia tworzenie i zarządzanie grafikami pracy pracowników. Dzięki jej funkcjonalnościom można łatwo przydzielać zmiany, śledzić dostępność pracowników i reagować na zmiany w czasie rzeczywistym. "Dater" zapewnia przejrzystą komunikację między zarządem a pracownikami, minimalizując ryzyko konfliktów grafikowych i zwiększając efektywność planowania zasobów ludzkich. To narzędzie, które stanowi most między elastycznym harmonogramowaniem a potrzebami operacyjnymi firmy.</p>
        <h5>Masz już konto? Zaloguj się poniżej</h5>
        <form method='POST'>
            {% csrf_token %} 
            {{ form.as_p }}
            <button type="submit" class="button">Log in</button>
        </form>
        <h5>Nie masz konta a dostałeś swój numer zarejestruj się tutaj:</h5>
        <a class="button" href="{% url 'accounts:user_register' %}">Rejestracja użytkownika</a>
        <h5>Chcesz efektywniej zarządzać swoim zespołem/firmą? Zapraszamy do zarejestrowania firmy:</h5>
        <a class="button" href="{% url 'accounts:company_register' %}">Rejestracja firmy</a>
    </div>
</div>
</body>
</html>

schedule_app/accounts/templates/accounts/register_company.html
<body>
  <h2>Rejestracja Firmy</h2>
  <form method="post">
      {% csrf_token %}
      <fieldset>
          <legend>Informacje o Użytkowniku:</legend>
          {{ user_form.as_p }}
      </fieldset>

      <fieldset>
          <legend>Informacje o Firmie:</legend>
          {{ company_form.as_p }}
      </fieldset>

      <button type="submit">Zarejestruj</button>
  </form>
</body>

schedule_app/accounts/templates/accounts/register_user.html
<form method='POST'>
  {% csrf_token %} 
  {{ form.as_p }}
  <button type="submit">Log in</button>
</form>